"""
Generates an interactive HTML5 dashboard representing the pipeline status.
"""

import os
import json
from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Agentic HTML5 Parser - Pipeline Report</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 20px; background-color: #f4f7f6; }
        .container { max-width: 1000px; margin: auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        .card { border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .pass { border-left: 5px solid #27ae60; }
        .fail { border-left: 5px solid #e74c3c; }
        .score { font-size: 24px; font-weight: bold; }
        .violation { color: #c0392b; list-style-type: square; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Pipeline Execution Report (v1.3.0)</h1>
        
        {% for run in runs %}
        <div class="card {{ 'pass' if run.audit.status == 'PASS' else 'fail' }}">
            <h2>Test Case: {{ run.label }}</h2>
            <p><strong>Compliance Score:</strong> <span class="score">{{ run.audit.score }}</span></p>
            <p><strong>Differential Oracle:</strong> {{ 'MATCHED' if run.differential.matches else 'DISCREPANCY' }}</p>
            <p><strong>Integrity:</strong> {{ 'VALID' if run.integrity.valid else 'INVALID' }}</p>
            
            {% if run.audit.violations %}
            <h3>Violations:</h3>
            <ul>
                {% for v in run.audit.violations %}
                <li class="violation">{{ v }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        {% endfor %}
        
        <p style="text-align: center; color: #7f8c8d; margin-top: 40px;">Generated by Agentic Pipeline Reporter</p>
    </div>
</body>
</html>
"""

def main():
    # Load simulation results from runs/
    runs = []
    runs_dir = "runs"
    if os.path.exists(runs_dir):
        for run_name in os.listdir(runs_dir):
            run_path = os.path.join(runs_dir, run_name, "report.json")
            if os.path.exists(run_path):
                with open(run_path, "r") as f:
                    runs.append(json.load(f))
    
    if not runs:
        print("[!] No simulation runs found. Run 'python run_all.py' first.")
        return

    # Render Template
    print("[*] Generating report.html...")
    template = Template(HTML_TEMPLATE)
    html_content = template.render(runs=runs)
    
    with open("report.html", "w") as f:
        f.write(html_content)
        
    print("[+] Dashboard generated: report.html")

if __name__ == "__main__":
    main()
